name: TOON2AVIF CI
run-name: T2Avif - ${{ inputs.ChapterRange }} - ${{ inputs.Input_Directory }}

on:
  workflow_dispatch:
    inputs:
      Input_Directory:
        description: "MDx Input Directory"
        required: true
        type: string
      Output_Directory:
        description: "MDx Output Dir (Optional)"
        required: false
        type: string
      chWidth:
        description: "Chapter Per Job"
        required: true
        type: choice
        options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "7"
        default: "2"
      ChapterRange:
        description: "RegEx Range of Chapters, OR all"
        required: true
        type: string
        default: "all"
      QScale:
        description: "AOMEnc QScale"
        required: true
        type: number
        default: 42
      Range:
        description: "YUV Color Range, JPEG>Full"
        required: true
        type: choice
        options:
        - j
        - f
        default: j
      Optimization:
        description: "Sharpness (0|1) + Denoise(0|1|wavelet|wavelet+aom)"
        required: true
        type: choice
        options:
        - "0-0"
        - "0-w"
        - "0-1"
        - "1-0"
        - "1-w"
        - "1-1"
        - "1-x"
        default: "1-0"
      TilingThreshold:
        description: "Tiling Threshold, 416<x<512<y<1024"
        required: true
        type: number
        default: 512
      SkipSmallPics:
        description: "Skip Smaller Pics, x<(2*TilingThreshold)?"
        required: true
        type: boolean
        default: true

env:
  BaseScript_Hash: "33dccb6d2b4418a5062b894c0d1c67b4"
  RCLONE_CONFIG_HASH: ${{ secrets.RCLONE_CONFIG_HASH }}
  Input_Directory: ${{ github.event.inputs.Input_Directory }}

jobs:
  prepare:
    name: MatrixGen | ${{ inputs.ChapterRange }}
    runs-on: ubuntu-24.04
    env:
      chWidth: ${{ github.event.inputs.chWidth }}
      ChapterRange: ${{ github.event.inputs.ChapterRange }}

    outputs:
      matrix: ${{ steps.set-params.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
          show-progress: false
      - name: Set Git Configs & Secrets
        uses: rokibhasansagar/custom_workflows/git_config@main
        with:
          credential: "yes"
          git_cookies: "no"
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Create EncMatrix
        id: set-params
        run: |
          # Get GIST latest Revision number
          export latestRevision=$(curl -sL "https://gist.github.com/rokibhasansagar/${BaseScript_Hash}/" | grep "/img2avif\.converter\.sh" | awk -F'/raw/' '{print $2}' | awk -F'/' '{print $1}')
          echo -e "[i] Using ${latestRevision} as latestRevision"
          # Generate Workflow Matrix
          curl -sL "https://gist.github.com/rokibhasansagar/${BaseScript_Hash}/raw/${latestRevision}/xRangeExpander.sh" -O
          sed -i 's/__RANGE__/'"${ChapterRange,,}"'/g' ./xRangeExpander.sh
          source ./xRangeExpander.sh && rm ./xRangeExpander.sh
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT
          echo -e "[i] Generated Matrix: ${matrix}"

  toon2avif:
    # name: ${{ inputs.Input_Directory }} - ${{ env.jobrange }} Q${{ env.Qscale }}
    runs-on: ubuntu-24.04
    needs: prepare

    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    env:
      jobrange: ${{ matrix.jobrange }}
      QScale: ${{ github.event.inputs.QScale }}
      Range: ${{ github.event.inputs.Range }}
      Optimization: ${{ github.event.inputs.Optimization }}
      TilingThreshold: ${{ github.event.inputs.TilingThreshold }}
      SkipSmallPics: ${{ github.event.inputs.SkipSmallPics }}
      LongStrip: true

    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
          show-progress: false
      - name: Set Git Configs & Secrets
        uses: rokibhasansagar/custom_workflows/git_config@main
        with:
          credential: "yes"
          git_cookies: "no"
        env:
          PAT: ${{ secrets.GH_TOKEN }}
      - name: Workstation
        env:
          Output_Directory: ${{ github.event.inputs.Output_Directory || github.event.inputs.Input_Directory }}
        run: |
          echo "::group::[i] Setup tools"
          # Get GIST latest Revision number
          export latestRevision=$(curl -sL "https://gist.github.com/rokibhasansagar/${BaseScript_Hash}/" | grep "/img2avif\.converter\.sh" | awk -F'/raw/' '{print $2}' | awk -F'/' '{print $1}')
          echo -e "[i] Using ${latestRevision} as latestRevision"
          curl -sL "https://gist.github.com/rokibhasansagar/${BaseScript_Hash}/raw/${latestRevision}/zToolsetup.sh" -O
          source ./zToolsetup.sh && rm ./zToolsetup.sh
          echo "::endgroup::"
          mkdir -p ~/data && cd ~/data
          if [[ ${Output_Directory} == "" ]]; then
            if grep -q "\s" <<<"${Input_Directory}"; then
              export Output_Directory=$(sed 's/[!?.~]//g;s/'\''//g;s/!//g;s/\s/./g' <<<"${Input_Directory}")
            else
              export Output_Directory="${Input_Directory}"
            fi
          fi
          # Core libaom Converter Scriptlet
          curl -sL "https://gist.github.com/rokibhasansagar/${BaseScript_Hash}/raw/${latestRevision}/img2avif.core.v1.sh" -O
          # Main AIO Converter + Downloader/Uploader
          curl -sL "https://gist.github.com/rokibhasansagar/${BaseScript_Hash}/raw/${latestRevision}/img2avif.converter.sh" -O
          export xRange=$(sed 's/\+/ /g' <<<"${jobrange}")
          sed -i 's/__JOBRANGE__/'"${xRange}"'/g' ./img2avif.converter.sh
          source ./img2avif.converter.sh

